import warnings
import os
from colorama import init, Fore, Style
from pydantic import BaseModel, Field
from typing import List

from langchain_community.document_loaders.generic import GenericLoader
from langchain_community.document_loaders.parsers import LanguageParser
from langchain_text_splitters import Language, RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_ollama import ChatOllama
from langchain_chroma import Chroma

from langchain_classic.chains import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import ChatPromptTemplate

warnings.filterwarnings("ignore")
init(autoreset=True)

class CodeFile(BaseModel):
    filepath: str = Field(description="Path to the file to create or update, e.g., src/new_module.py")
    code: str = Field(description="The complete, working code.")

class AgentResponse(BaseModel):
    explanation: str = Field(description="Brief explanation of what was built or modified.")
    files: List[CodeFile] = Field(description="List of files generated by the AI.")

class TraverseEngine:
    def __init__(self, path=".", exclude=None, model="qwen3-coder:480b-cloud"):
        if exclude is None:
            exclude = ["**/node_modules/**", "**/target/**", "**/build/**", "**/.venv/**"]
        self.path = path
        self.exc = exclude
        self.model = model
    
    def traverse(self):
        suffixes = ['.py', '.js', '.ts', '.c', '.cpp', '.rs', '.h', '.txt', '.md', '.html']
        docs = []
        seen_sources = set()
        
        for glob_pattern in ["**/[!.]*", "*"]:
            loader = GenericLoader.from_filesystem(
                path=self.path,
                glob=glob_pattern,
                exclude=self.exc,
                suffixes=suffixes,
                parser=LanguageParser()
            )
            
            for doc in loader.load():
                source = doc.metadata.get("source")
                if source not in seen_sources:
                    seen_sources.add(source)
                    docs.append(doc)

        print(f"\n{Fore.LIGHTYELLOW_EX}Total documents indexed: {len(docs)}{Style.RESET_ALL}")
        
        splitters = {
            ".py": RecursiveCharacterTextSplitter.from_language(language=Language.PYTHON, chunk_size=2000, chunk_overlap=200),
            ".cpp": RecursiveCharacterTextSplitter.from_language(language=Language.CPP, chunk_size=2000, chunk_overlap=200),
            ".rs": RecursiveCharacterTextSplitter.from_language(language=Language.RUST, chunk_size=2000, chunk_overlap=200),
            ".js": RecursiveCharacterTextSplitter.from_language(language=Language.JS, chunk_size=2000, chunk_overlap=200),
            ".ts": RecursiveCharacterTextSplitter.from_language(language=Language.TS, chunk_size=2000, chunk_overlap=200), 
            ".c": RecursiveCharacterTextSplitter.from_language(language=Language.C, chunk_size=2000, chunk_overlap=200),
            ".h": RecursiveCharacterTextSplitter.from_language(language=Language.C, chunk_size=2000, chunk_overlap=200),
            ".html": RecursiveCharacterTextSplitter.from_language(language=Language.HTML, chunk_size=2000, chunk_overlap=200),
        }

        fallback_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)

        texts = []
        for doc in docs:
            ext = os.path.splitext(doc.metadata.get("source", ""))[1]
            splitter = splitters.get(ext, fallback_splitter)
            texts.extend(splitter.split_documents([doc]))

        return Chroma.from_documents(
            documents=texts, 
            embedding=HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
        )

    def loadQueryModel(self, vector_store):
        llm = ChatOllama(model=self.model, temperature=0)
        prompt = ChatPromptTemplate.from_template("""
            You are a helpful assistant with full access to the codebase.
            Use the following context to explain or answer the user's question.
            Context: {context}
            Question: {input}
        """)

        combine_docs_chain = create_stuff_documents_chain(llm, prompt)
        return create_retrieval_chain(vector_store.as_retriever(), combine_docs_chain)
    
    def loadAIAgent(self, vector_store, SchemeClass):
        llm = ChatOllama(model=self.model, temperature=0, format="json")
        parser = PydanticOutputParser(pydantic_object=SchemeClass)

        prompt = ChatPromptTemplate.from_template("""
            You are an expert AI architect with full access to the codebase.
            Use the following retrieved context to implement the user's request.
            If the user asks to add a feature or file, generate the necessary code.

            Context: {context}
            Question: {input}

            You must format your output strictly as a JSON object matching the following instructions:
            {format_instructions}
        """)

        def format_docs(docs):
            return "\n\n".join(doc.page_content for doc in docs)

        return (
            {
                "context": vector_store.as_retriever() | format_docs, 
                "input": RunnablePassthrough(),
                "format_instructions": lambda _: parser.get_format_instructions()
            }
            | prompt
            | llm
            | parser
        )